# Numpy

In [ ]:
import numpy as np

## Array


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.4)

array([2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4])

In [ ]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[1]

np.int64(2)

In [ ]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi Dimensional Arrays

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
n
n[0,1]

np.int64(2)

In [ ]:
## to access rows
n[0]

array([1, 2, 3])

In [ ]:
## to access columns

n[:0]

array([], shape=(0, 3), dtype=int64)

## Random Arrays
