# Numpy useful tips

In [1]:
import numpy as np

## Array


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.4)

array([2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4])

In [5]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
a[1]

np.int64(2)

In [7]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi Dimensional Arrays

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
n
n[0,1]

np.int64(2)

In [13]:
## to access rows
n[0]

array([1, 2, 3])

In [14]:
## to access columns

n[:0]

array([], shape=(0, 3), dtype=int64)

## Random Arrays


In [15]:
np.random.seed(2)## setting the seed to reproduce same numbers
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [16]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
##random integers
np.random.seed(2)
np.random.randint(low=0,high=20,size=(5,2))

array([[ 8, 15],
       [13,  8],
       [11, 18],
       [11,  8],
       [ 7,  2]])

### Elementwise operations

In [18]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [19]:
10*(a*2)

array([ 0, 20, 40, 60, 80])

## compare elements

In [20]:
a>=2

array([False, False,  True,  True,  True])

In [21]:
##compare

a.min()

np.int64(0)