## Vector operations

In [2]:
import numpy as np

u=np.array([1,2,3,4])
v=np.array([3,4,5,6])


In [5]:
print(u+v)
print(u*v)

[ 4  6  8 10]
[ 3  8 15 24]


In [5]:
v.shape[0]

4

In [6]:
##vector multiplication

def vector_multiplication (u,v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]##it could nbe v as well both have same shape
    result=0.0
    for i in range(n):
        result=result+u[i]*v[i]
    return result

In [7]:
vector_multiplication(u,v)

np.float64(50.0)

In [10]:
## matrix vector multiplication
a=np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
b=np.array([1,0.5,2,1])

print(a.shape)
print(b.shape)

(3, 4)
(4,)


In [12]:

# for cross multiplication columns of vect 1 should match rows of vec 2
a.dot(b)


array([20. ,  6. ,  8.5])